### PR TITLE
Fix bug #19 with create team

### LINKED ISSUE #19: Bug with "Create Team"
To create a new team you need to press "create" three times. At the first time it cleares the current team Selection, at the second time it rearranges the selection fields and at the first time it creates the new teams and goes back to standart selection.

### PR DESCRIPTION
**Pull request by tommy33790**
### :scroll: Description

Changes proposed in this pull request:
* fixed team creation
* fixed handling of default team
* improved default team selection

### :hammer: Breaking Changes

* selected team is stored by name instead of index

### :white_check_mark: Checklist:

- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the documentation (if necessary)

### CODE REVIEW

File: src/main/kotlin/org/openbase/planetsudo/view/MainGUI.kt [hunk 1]
```diff
@@ -462,6 +462,7 @@ class MainGUI : JFrame, PropertyChangeListener {
     private fun jMenuItem4ActionPerformed(evt: ActionEvent) { // GEN-FIRST:event_jMenuItem4ActionPerformed
         try {
             resetDefaultTeam()
+            configurationPanel?.enableDefaultTeamSelection()
```
Comment (DivineThreepwood) [inline src/main/kotlin/org/openbase/planetsudo/view/MainGUI.kt:465]: How about moving `configurationPanel?.enableDefaultTeamSelection()` into the end of fun `resetDefaultTeam()`. Since after resetting the default team it always makes sense to enable the selection again.

**Review by DivineThreepwood — CHANGES_REQUESTED** [review]
only one minor change requested.

**Review by DivineThreepwood — APPROVED** [review]

**Comment by DivineThreepwood** [comment]
Works like a charm :)
